<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="67046" started-at="2019-11-15T12:17:36 CST" finished-at="2019-11-15T12:18:43 CST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:testRunener.TestRunner@34c4973]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="67046" started-at="2019-11-15T12:17:36 CST" finished-at="2019-11-15T12:18:43 CST">
      <class name="testRunener.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:testRunener.TestRunner@34c4973]" name="setUpClass" is-config="true" duration-ms="410" started-at="2019-11-15T12:17:36 CST" finished-at="2019-11-15T12:17:36 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:testRunener.TestRunner@34c4973]" name="runScenario" duration-ms="18483" started-at="2019-11-15T12:17:37 CST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2019-11-15T12:17:55 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user i should be able to log in with valid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Loging test"]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[There are undefined steps]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: There are undefined steps
at io.cucumber.testng.TestCaseResultListener.getError(TestCaseResultListener.java:60)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:83)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="SKIP" signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:testRunener.TestRunner@34c4973]" name="runScenario" duration-ms="16795" started-at="2019-11-15T12:17:55 CST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2019-11-15T12:18:12 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user i should not be able to log in with invalid email"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Loging test"]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[There are undefined steps]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: There are undefined steps
at io.cucumber.testng.TestCaseResultListener.getError(TestCaseResultListener.java:60)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:83)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:testRunener.TestRunner@34c4973]" name="runScenario" duration-ms="17843" started-at="2019-11-15T12:18:12 CST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2019-11-15T12:18:30 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user i should not be able to log in without email"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Loging test"]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[session not created
from chrome not reachable
  (Session info: chrome=78.0.3904.97)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-4PDFKMD', ip: '10.108.1.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00E5A903+1550595]
Ordinal0 [0x00DDA701+1025793]
Ordinal0 [0x00D5C58E+509326]
Ordinal0 [0x00D562C2+484034]
Ordinal0 [0x00D5699B+485787]
Ordinal0 [0x00D57B05+490245]
Ordinal0 [0x00D53A85+473733]
Ordinal0 [0x00D5D330+512816]
Ordinal0 [0x00D0B649+177737]
Ordinal0 [0x00D0A8ED+174317]
Ordinal0 [0x00D08CDB+167131]
Ordinal0 [0x00CF144A+70730]
Ordinal0 [0x00CF24D0+74960]
Ordinal0 [0x00CF2469+74857]
Ordinal0 [0x00DF42C7+1131207]
GetHandleVerifier [0x00EF70FD+523789]
GetHandleVerifier [0x00EF6E90+523168]
GetHandleVerifier [0x00EFE1E7+552695]
GetHandleVerifier [0x00EF78FA+525834]
Ordinal0 [0x00DEB7FC+1095676]
Ordinal0 [0x00DF633B+1139515]
Ordinal0 [0x00DF64A3+1139875]
Ordinal0 [0x00DF5425+1135653]
BaseThreadInitThunk [0x76216359+25]
RtlGetAppContainerNamedObjectPath [0x77267B74+228]
RtlGetAppContainerNamedObjectPath [0x77267B44+180]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: session not created
from chrome not reachable
  (Session info: chrome=78.0.3904.97)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-4PDFKMD', ip: '10.108.1.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00E5A903+1550595]
Ordinal0 [0x00DDA701+1025793]
Ordinal0 [0x00D5C58E+509326]
Ordinal0 [0x00D562C2+484034]
Ordinal0 [0x00D5699B+485787]
Ordinal0 [0x00D57B05+490245]
Ordinal0 [0x00D53A85+473733]
Ordinal0 [0x00D5D330+512816]
Ordinal0 [0x00D0B649+177737]
Ordinal0 [0x00D0A8ED+174317]
Ordinal0 [0x00D08CDB+167131]
Ordinal0 [0x00CF144A+70730]
Ordinal0 [0x00CF24D0+74960]
Ordinal0 [0x00CF2469+74857]
Ordinal0 [0x00DF42C7+1131207]
GetHandleVerifier [0x00EF70FD+523789]
GetHandleVerifier [0x00EF6E90+523168]
GetHandleVerifier [0x00EFE1E7+552695]
GetHandleVerifier [0x00EF78FA+525834]
Ordinal0 [0x00DEB7FC+1095676]
Ordinal0 [0x00DF633B+1139515]
Ordinal0 [0x00DF64A3+1139875]
Ordinal0 [0x00DF5425+1135653]
BaseThreadInitThunk [0x76216359+25]
RtlGetAppContainerNamedObjectPath [0x77267B74+228]
RtlGetAppContainerNamedObjectPath [0x77267B44+180]

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
at stepDefinition.GivenLogin.user_open_the_browser_to_the_page(GivenLogin.java:28)
at ✽.user open the browser to the page(file:src/test/resources/features/login.feature:36)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:testRunener.TestRunner@34c4973]" name="runScenario" duration-ms="13187" started-at="2019-11-15T12:18:30 CST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2019-11-15T12:18:43 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user i should not be able to log in without password"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Loging test"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login - My Store] but found [There is 1 error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login - My Store] but found [There is 1 error]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefinition.ThenLogin.user_should_not_be_in_the_profile_page(ThenLogin.java:25)
at ✽.user should not be in the profile page(file:src/test/resources/features/login.feature:48)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:testRunener.TestRunner@34c4973]" name="tearDownClass" is-config="true" duration-ms="21" started-at="2019-11-15T12:18:43 CST" finished-at="2019-11-15T12:18:43 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRunener.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
